package hello.controller;

import java.util.HashMap;
import java.util.Map;

import hello.Login;
import hello.dbStructure.Conversation;
import hello.dbStructure.Message;
import hello.dbStructure.User;
import hello.repositories.ConversationRepository;
import hello.repositories.MessageRepository;
import hello.repositories.UserRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

@RestController
public class LoginController {

    @Autowired // Which is auto-generated by Spring, we will use it to handle the data
    private UserRepository userRepository;


    class LoginResponse{
        private final String token;

        public int getId() {
            return id;
        }

        public void setId(int id) {
            this.id = id;
        }

        private int id;

        public LoginResponse(String token, int id){
            this.token = token;
            this.id = id;
        }
        public String getToken(){
            return token;
        }
    }

    static Map<String, Login> connectedUser  = new HashMap<>();

    @PostMapping("/login")
    @ResponseBody
    public LoginResponse login(@RequestBody Map<String, String> payload) {




        Login login = new Login(payload.get("username"), payload.get("password"));
        if(login.checkLogin(userRepository)) {
            return new LoginResponse(login.getToken(), userRepository.getId(login.getToken()));
        }
        else
            return new LoginResponse("LoginFailed",-1);
    }

    @PostMapping("/register")
    public String register(@RequestBody Login login ) {
        return login.getToken();
    }

    @GetMapping("/logout")
    public String logout(@RequestBody Login login ) {
        return login.getToken();
    }



}
